/*
  # Populate Product Catalog - Épicerie, Produits laitiers, Viandes

  Adds categories 3-6 to the product catalog
*/

-- Category 3: Épicerie salée
INSERT INTO product_catalog (name, category, subcategory, search_terms) VALUES
('Spaghetti', 'Épicerie salée / Conserves', 'Pâtes & riz', 'spaghetti pates'),
('Penne', 'Épicerie salée / Conserves', 'Pâtes & riz', 'penne pates'),
('Farfalle', 'Épicerie salée / Conserves', 'Pâtes & riz', 'farfalle pates'),
('Fusilli', 'Épicerie salée / Conserves', 'Pâtes & riz', 'fusilli pates'),
('Macaroni', 'Épicerie salée / Conserves', 'Pâtes & riz', 'macaroni pates'),
('Coquillettes', 'Épicerie salée / Conserves', 'Pâtes & riz', 'coquillettes pates'),
('Lasagnes', 'Épicerie salée / Conserves', 'Pâtes & riz', 'lasagnes pates'),
('Nouilles asiatiques', 'Épicerie salée / Conserves', 'Pâtes & riz', 'nouilles asiatiques riz ble ramen'),
('Riz blanc', 'Épicerie salée / Conserves', 'Pâtes & riz', 'riz blanc long basmati jasmin'),
('Riz complet', 'Épicerie salée / Conserves', 'Pâtes & riz', 'riz complet'),
('Riz parfumé', 'Épicerie salée / Conserves', 'Pâtes & riz', 'riz parfume'),
('Riz à sushi', 'Épicerie salée / Conserves', 'Pâtes & riz', 'riz sushi'),
('Semoule de couscous', 'Épicerie salée / Conserves', 'Pâtes & riz', 'semoule couscous'),
('Boulgour', 'Épicerie salée / Conserves', 'Pâtes & riz', 'boulgour'),
('Quinoa', 'Épicerie salée / Conserves', 'Pâtes & riz', 'quinoa'),
('Lentilles vertes', 'Épicerie salée / Conserves', 'Légumineuses', 'lentilles vertes'),
('Lentilles corail', 'Épicerie salée / Conserves', 'Légumineuses', 'lentilles corail'),
('Pois chiches', 'Épicerie salée / Conserves', 'Légumineuses', 'pois chiches'),
('Haricots rouges', 'Épicerie salée / Conserves', 'Légumineuses', 'haricots rouges'),
('Haricots blancs', 'Épicerie salée / Conserves', 'Légumineuses', 'haricots blancs'),
('Flageolets', 'Épicerie salée / Conserves', 'Légumineuses', 'flageolets'),
('Pois cassés', 'Épicerie salée / Conserves', 'Légumineuses', 'pois casses'),
('Maïs en boîte', 'Épicerie salée / Conserves', 'Conserves de légumes', 'mais boite conserve'),
('Petits pois carottes', 'Épicerie salée / Conserves', 'Conserves de légumes', 'petits pois carottes conserve'),
('Haricots verts conserve', 'Épicerie salée / Conserves', 'Conserves de légumes', 'haricots verts conserve'),
('Ratatouille conserve', 'Épicerie salée / Conserves', 'Conserves de légumes', 'ratatouille conserve'),
('Tomates pelées', 'Épicerie salée / Conserves', 'Conserves de légumes', 'tomates pelees conserve'),
('Tomates concassées', 'Épicerie salée / Conserves', 'Conserves de légumes', 'tomates concassees conserve'),
('Purée de tomates', 'Épicerie salée / Conserves', 'Conserves de légumes', 'puree tomates conserve'),
('Thon à l''huile', 'Épicerie salée / Conserves', 'Conserves de poisson', 'thon huile conserve'),
('Thon au naturel', 'Épicerie salée / Conserves', 'Conserves de poisson', 'thon naturel conserve'),
('Sardines à l''huile', 'Épicerie salée / Conserves', 'Conserves de poisson', 'sardines huile conserve'),
('Sardines à la tomate', 'Épicerie salée / Conserves', 'Conserves de poisson', 'sardines tomate conserve');

-- Category 4: Épicerie sucrée
INSERT INTO product_catalog (name, category, subcategory, search_terms) VALUES
('Farine de blé', 'Épicerie sucrée', 'Farine & préparations', 'farine ble t45 t55 t65'),
('Farine complète', 'Épicerie sucrée', 'Farine & préparations', 'farine complete'),
('Levure chimique', 'Épicerie sucrée', 'Farine & préparations', 'levure chimique'),
('Levure boulangère', 'Épicerie sucrée', 'Farine & préparations', 'levure boulangere seche'),
('Sucre blanc', 'Épicerie sucrée', 'Sucres & édulcorants', 'sucre blanc'),
('Sucre roux', 'Épicerie sucrée', 'Sucres & édulcorants', 'sucre roux'),
('Cassonade', 'Épicerie sucrée', 'Sucres & édulcorants', 'cassonade sucre'),
('Miel', 'Épicerie sucrée', 'Sucres & édulcorants', 'miel'),
('Sirop d''érable', 'Épicerie sucrée', 'Sucres & édulcorants', 'sirop erable'),
('Confiture de fraise', 'Épicerie sucrée', 'Confitures & pâtes à tartiner', 'confiture fraise'),
('Confiture d''abricot', 'Épicerie sucrée', 'Confitures & pâtes à tartiner', 'confiture abricot'),
('Pâte à tartiner chocolat', 'Épicerie sucrée', 'Confitures & pâtes à tartiner', 'pate tartiner chocolat noisettes'),
('Corn flakes', 'Épicerie sucrée', 'Céréales petit-déjeuner', 'corn flakes cereales'),
('Muesli', 'Épicerie sucrée', 'Céréales petit-déjeuner', 'muesli fruits secs cereales'),
('Granola', 'Épicerie sucrée', 'Céréales petit-déjeuner', 'granola chocolat cereales'),
('Flocons d''avoine', 'Épicerie sucrée', 'Céréales petit-déjeuner', 'flocons avoine cereales'),
('Biscuits au beurre', 'Épicerie sucrée', 'Biscuits & gâteaux secs', 'biscuits beurre'),
('Petits beurres', 'Épicerie sucrée', 'Biscuits & gâteaux secs', 'petits beurres biscuits'),
('Cookies chocolat', 'Épicerie sucrée', 'Biscuits & gâteaux secs', 'cookies chocolat biscuits'),
('Madeleines', 'Épicerie sucrée', 'Biscuits & gâteaux secs', 'madeleines biscuits'),
('Chocolat noir', 'Épicerie sucrée', 'Chocolat & bonbons', 'chocolat noir tablette'),
('Chocolat au lait', 'Épicerie sucrée', 'Chocolat & bonbons', 'chocolat lait tablette'),
('Bonbons gélifiés', 'Épicerie sucrée', 'Chocolat & bonbons', 'bonbons gelifies');

-- Category 5: Produits laitiers & œufs
INSERT INTO product_catalog (name, category, subcategory, search_terms) VALUES
('Lait entier', 'Produits laitiers & œufs', 'Lait', 'lait entier uht'),
('Lait demi-écrémé', 'Produits laitiers & œufs', 'Lait', 'lait demi ecreme'),
('Lait écrémé', 'Produits laitiers & œufs', 'Lait', 'lait ecreme'),
('Lait sans lactose', 'Produits laitiers & œufs', 'Lait', 'lait sans lactose'),
('Boisson soja', 'Produits laitiers & œufs', 'Lait', 'boisson soja vegetale'),
('Boisson amande', 'Produits laitiers & œufs', 'Lait', 'boisson amande vegetale'),
('Yaourts nature', 'Produits laitiers & œufs', 'Yaourts & desserts', 'yaourts nature'),
('Yaourts aromatisés', 'Produits laitiers & œufs', 'Yaourts & desserts', 'yaourts aromatises'),
('Yaourts aux fruits', 'Produits laitiers & œufs', 'Yaourts & desserts', 'yaourts fruits'),
('Dèguè de petit mil', 'Produits laitiers & œufs', 'Yaourts & desserts', 'degue petit mil'),
('Dèguè de sémoule', 'Produits laitiers & œufs', 'Yaourts & desserts', 'degue semoule'),
('Fromage blanc', 'Produits laitiers & œufs', 'Yaourts & desserts', 'fromage blanc'),
('Crème dessert chocolat', 'Produits laitiers & œufs', 'Yaourts & desserts', 'creme dessert chocolat'),
('Beurre doux', 'Produits laitiers & œufs', 'Beurre & matières grasses', 'beurre doux'),
('Beurre demi-sel', 'Produits laitiers & œufs', 'Beurre & matières grasses', 'beurre demi sel'),
('Margarine', 'Produits laitiers & œufs', 'Beurre & matières grasses', 'margarine'),
('Crème fraîche', 'Produits laitiers & œufs', 'Crèmes', 'creme fraiche epaisse'),
('Crème liquide', 'Produits laitiers & œufs', 'Crèmes', 'creme liquide'),
('Emmental râpé', 'Produits laitiers & œufs', 'Fromages', 'emmental rape fromage'),
('Gruyère râpé', 'Produits laitiers & œufs', 'Fromages', 'gruyere rape fromage'),
('Mozzarella', 'Produits laitiers & œufs', 'Fromages', 'mozzarella fromage'),
('Feta', 'Produits laitiers & œufs', 'Fromages', 'feta fromage'),
('Fromage à tartiner', 'Produits laitiers & œufs', 'Fromages', 'fromage tartiner'),
('Œufs (6)', 'Produits laitiers & œufs', 'Œufs', 'oeufs boite 6'),
('Œufs (10)', 'Produits laitiers & œufs', 'Œufs', 'oeufs boite 10');

-- Category 6: Viandes / Poissons / Charcuterie
INSERT INTO product_catalog (name, category, subcategory, search_terms) VALUES
('Bœuf haché', 'Viandes / Poissons / Charcuterie', 'Viandes fraîches', 'boeuf hache viande'),
('Steaks de bœuf', 'Viandes / Poissons / Charcuterie', 'Viandes fraîches', 'steaks boeuf viande'),
('Poulet entier', 'Viandes / Poissons / Charcuterie', 'Viandes fraîches', 'poulet entier viande'),
('Cuisses de poulet', 'Viandes / Poissons / Charcuterie', 'Viandes fraîches', 'cuisses poulet viande'),
('Filets de poulet', 'Viandes / Poissons / Charcuterie', 'Viandes fraîches', 'filets poulet viande'),
('Escalopes de dinde', 'Viandes / Poissons / Charcuterie', 'Viandes fraîches', 'escalopes dinde viande'),
('Côtelettes d''agneau', 'Viandes / Poissons / Charcuterie', 'Viandes fraîches', 'cotelettes agneau viande'),
('Jambon cuit', 'Viandes / Poissons / Charcuterie', 'Charcuterie', 'jambon cuit charcuterie'),
('Jambon cru', 'Viandes / Poissons / Charcuterie', 'Charcuterie', 'jambon cru charcuterie'),
('Saucisson sec', 'Viandes / Poissons / Charcuterie', 'Charcuterie', 'saucisson sec charcuterie'),
('Saucisse', 'Viandes / Poissons / Charcuterie', 'Charcuterie', 'saucisse strasbourg hotdog charcuterie'),
('Filets de saumon', 'Viandes / Poissons / Charcuterie', 'Poissons & fruits de mer', 'filets saumon poisson'),
('Filets de cabillaud', 'Viandes / Poissons / Charcuterie', 'Poissons & fruits de mer', 'filets cabillaud poisson'),
('Crevettes', 'Viandes / Poissons / Charcuterie', 'Poissons & fruits de mer', 'crevettes poisson'),
('Nuggets de poulet', 'Viandes / Poissons / Charcuterie', 'Produits transformés', 'nuggets poulet'),
('Cordons bleus', 'Viandes / Poissons / Charcuterie', 'Produits transformés', 'cordons bleus');
